urls:
  - url: "https://www.ticketmaster.co.uk/ariana-grande-the-eternal-sunshine-tour-london-15-08-2026/event/3500631C8EA13055"
    search_text: "0 No results"
    mode: "disappears"
    note: "Ariana Grande The Eternal Sunshine Tour London 15 Aug 2026"
  - url: "https://www.ticketmaster.co.uk/ariana-grande-the-eternal-sunshine-tour-london-16-08-2026/event/3500631C937630FA"
    search_text: "0 No results"
    mode: "disappears"
    note: "Ariana Grande The Eternal Sunshine Tour London 16 Aug 2026"
  - url: "https://www.ticketmaster.co.uk/ariana-grande-the-eternal-sunshine-tour-london-19-08-2026/event/3500631C950D310B"
    search_text: "0 No results"
    mode: "disappears"
    note: "Ariana Grande The Eternal Sunshine Tour London 19 Aug 2026"
  - url: "https://www.ticketmaster.co.uk/ariana-grande-the-eternal-sunshine-tour-london-20-08-2026/event/3500631C97193144"
    search_text: "0 No results"
    mode: "disappears"
    note: "Ariana Grande The Eternal Sunshine Tour London 20 Aug 2026"
  - url: "https://www.ticketmaster.co.uk/ariana-grande-the-eternal-sunshine-tour-london-23-08-2026/event/3500631C98A031B3"
    search_text: "0 No results"
    mode: "disappears"
    note: "Ariana Grande The Eternal Sunshine Tour London 23 Aug 2026"
  - url: "https://www.ticketmaster.co.uk/ariana-grande-the-eternal-sunshine-tour-london-24-08-2026/event/35006324F4E94EBB"
    search_text: "0 No results"
    mode: "disappears"
    note: "Ariana Grande The Eternal Sunshine Tour London 24 Aug 2026"
  - url: "https://www.ticketmaster.co.uk/ariana-grande-the-eternal-sunshine-tour-london-27-08-2026/event/35006324F4FE4F2A"
    search_text: "0 No results"
    mode: "disappears"
    note: "Ariana Grande The Eternal Sunshine Tour London 27 Aug 2026"
  - url: "https://www.ticketmaster.co.uk/ariana-grande-the-eternal-sunshine-tour-london-28-08-2026/event/35006324F5075024"
    search_text: "0 No results"
    mode: "disappears"
    note: "Ariana Grande The Eternal Sunshine Tour London 28 Aug 2026"
  - url: "https://www.ticketmaster.co.uk/ariana-grande-the-eternal-sunshine-tour-london-31-08-2026/event/35006324F4F54EF7"
    search_text: "0 No results"
    mode: "disappears"
    note: "Ariana Grande The Eternal Sunshine Tour London 31 Aug 2026"
  - url: "https://www.ticketmaster.co.uk/ariana-grande-the-eternal-sunshine-tour-london-01-09-2026/event/35006324F50F50D8"
    search_text: "0 No results"
    mode: "disappears"
    note: "Ariana Grande The Eternal Sunshine Tour London 1 Sep 2026"
